function addCardCertificatesInfo() {
  databaseCertificates.forEach(item => {
    createCardCertificatesInfo(item.title, item.description, item.thumbnail, item.hours, item.year, item.link)
  })
}

function createCardCertificatesInfo(title, description, thumbnail, hours, year, link) {
  const div = document.createElement("div")
  div.setAttribute("class", "section__box relative d-grid p-05 bg-dark-gray text-center")

  const chevronTopLeft = createSVG("chevron-top-left")
  const chevronTopRight = createSVG("chevron-top-right")
  const chevronBottomRight = createSVG("chevron-bottom-right")
  const chevronBottomLeft = createSVG("chevron-bottom-left")

  const h2 = document.createElement("h2")
  h2.setAttribute("class", "m-0")
  const h2Text = document.createTextNode(title)
  h2.appendChild(h2Text)
  const p = document.createElement("p")
  const pText = document.createTextNode(description)
  p.appendChild(pText)
  p.setAttribute("class", "mt-0")
  const pHours = document.createElement("p")
  const pHoursText = document.createTextNode(`Horas: ${hours}`)
  pHours.appendChild(pHoursText)
  pHours.setAttribute("class", "m-0")
  const pYear = document.createElement("p")
  const pYearText = document.createTextNode(`Año: ${year}`)
  pYear.appendChild(pYearText)
  pYear.setAttribute("class", "m-0")

  const aLink = document.createElement("a")
  const aLinkText = document.createTextNode("Link")
  aLink.appendChild(aLinkText)
  aLink.setAttribute("href", link)
  aLink.setAttribute("target", "_blanket")
  aLink.setAttribute("class", "section__button w-100 text-center border-radius-top-5 m-0-auto")
  const aLinkImg = document.createElement("a")
  aLinkImg.setAttribute("href", link)
  aLinkImg.setAttribute("target", "_blanket")
  const img = document.createElement("img")
  img.setAttribute("src", `./src/img/certificates/${thumbnail}`)
  img.setAttribute("loading", "lazy")
  img.setAttribute("alt", title)
  img.setAttribute("class", "w-100 h-250px object-fit-cover object-pos-center-top")
  aLinkImg.appendChild(img)

  div.appendChild(chevronTopLeft)
  div.appendChild(chevronTopRight)
  div.appendChild(chevronBottomRight)
  div.appendChild(chevronBottomLeft)
  div.appendChild(h2)
  div.appendChild(p)
  div.appendChild(pHours)
  div.appendChild(pYear)
  div.appendChild(aLinkImg)
  div.appendChild(aLink)
  certificates.appendChild(div)
}

addCardCertificatesInfo()