const createCardCertificatesInfo = (title, description, thumbnail,category, hours, year, link) =>{
  const div = document.createElement("div")
  div.setAttribute("class", "section__box pt-1 drop-shadow relative d-grid bg-dark-gray text-center opacityEffect")

  const chevronTopLeft = createSVG("chevron-top-left")
  const chevronTopRight = createSVG("chevron-top-right")

  const h3 = document.createElement("h3")
  h3.setAttribute("class", "m-0")
  const h3Text = document.createTextNode(title)
  h3.appendChild(h3Text)
  const p = document.createElement("p")
  const pText = document.createTextNode(description)
  p.appendChild(pText)
  p.setAttribute("class", "mt-0")


  const pCategory = document.createElement("p")
  const pCategoryText = document.createTextNode(`Categoría: ${category}`)
  pCategory.appendChild(pCategoryText)
  pCategory.setAttribute("class", "m-0")

  const pHours = document.createElement("p")
  const pHoursText = document.createTextNode(`Horas: ${hours}`)
  pHours.appendChild(pHoursText)
  pHours.setAttribute("class", "m-0")
  const pYear = document.createElement("p")
  const pYearText = document.createTextNode(`Año: ${year}`)
  pYear.appendChild(pYearText)
  pYear.setAttribute("class", "m-0")

  const aLink = document.createElement("a")
  const aLinkText = document.createTextNode("Link")
  aLink.appendChild(aLinkText)
  aLink.setAttribute("href", link)
  aLink.setAttribute("target", "_blank")
  aLink.setAttribute("class", "section__button w-100 text-center m-0-auto")
  const aLinkImg = document.createElement("a")
  aLinkImg.setAttribute("href", link)
  aLinkImg.setAttribute("target", "_blanket")
  aLinkImg.setAttribute("class", "p-0")
  const img = document.createElement("img")
  img.setAttribute("src", `https://ucarecdn.com/${thumbnail}/-/scale_crop/500x250/-/format/auto/-/quality/smart/`)
  img.setAttribute("loading", "lazy")
  img.setAttribute("alt", title)
  img.setAttribute("width", "500")
  img.setAttribute("height", "250")
  img.setAttribute("class", "w-100 pt-1 object-fit-cover object-pos-center-top border-radius-top-5 d-block")
  aLinkImg.appendChild(img)

  div.append(chevronTopLeft,chevronTopRight)
  div.append(h3,p,pHours,pYear,pCategory,aLinkImg,aLink)
  certificates.appendChild(div)
}